defaults:
  - /slam: default

instance: vipe.pipeline.default.DefaultAnnotationPipeline

init:
  camera_type: "pinhole"
  intrinsics: "geocalib"
  async_prefetch: true
  prefetch_queue_size: 16
  instance:
    kf_gap_sec: 2.0
    phrases:
      - person
      - animal
      - vehicle
      - ball
      - balloon
      - gun
      - pet
      - car
      - bus
    add_sky: true

slam:
  keyframe_thresh: 1.0
  keyframe_depth: pi3x_moge
  optimize_intrinsics: ${neq:${..init.intrinsics},"gt"}
  per_frame_intrinsics: true
  compute_ba_residual: true

post:
  depth_align_model: "pi3x_moge_perframe"
  pixel_limit: 255000
  window_size: 64
  overlap_size: 16
  align_lr_size: 64
  min_align_points: 200
  align_mode: "window_shared_ema"
  align_momentum: 0.99
  scale_clamp: [0.1, 10.0]
  shift_z_clamp: [-1000.0, 1000.0]
  align_source: "slam_map"
  moge_bs: 16

output:
  path: vipe_results/
  skip_exists: true
  save_artifacts: true
  save_slam_map: false
  save_slam_intermediate: true
  save_viz: true
  viz_downsample: 4
  viz_attributes: [['rgb', 'instance'], ['depth', 'pcd']]
