instance: vipe.pipeline.pi3x_only.Pi3XOnlyAnnotationPipeline

# Init configs
init:
  camera_type: "pinhole"
  intrinsics: "geocalib"
  instance:
    kf_gap_sec: 2.0
    phrases:
      - person
      - animal
      - vehicle
      - ball
      - balloon
      - gun
      - pet
      - car
      - bus
    add_sky: true

# Pi3X configuration
pi3x:
  vo:
    model: "yyfz233/Pi3X"
    chunk_size: 64
    overlap: 32
    conf_thre: 0.05
    dtype: "bf16"
    pose_convention: "c2w"
  depth:
    model: "yyfz233/Pi3X"
    pixel_limit: 255000
    batch_size: 8

# Output configs
output:
  path: vipe_results_pi3x_only/
  skip_exists: false
  save_artifacts: true
