#!/bin/bash
#SBATCH -A nvr_elm_llm
#SBATCH -p polar4,polar3,polar,grizzly
#SBATCH -t 04:00:00
#SBATCH -N 1
#SBATCH --mem 0
#SBATCH --gpus-per-node 8
#SBATCH --array=1-5%1
#SBATCH --exclusive
#SBATCH -J VIPE:OmniWorld-GROUP_ID
#SBATCH -o logs/omniworld_GROUP_ID_%A_%a.out
#SBATCH -e logs/omniworld_GROUP_ID_%A_%a.err

# ============================================================================
# OmniWorld Annotation Job Template
# This script is auto-generated by submit_all.sh
# GROUP_ID, CHUNK_START, CHUNK_END, __CHUNKS_PER_JOB__, __WINDOW_SIZE__, __OVERLAP__ are replaced when generating job scripts
# ============================================================================

# --- 1. Environment Setup ---
export MYHOME="$HOME"
MINIFORGE_ROOT="$MYHOME/miniforge3"
source "$MINIFORGE_ROOT/etc/profile.d/conda.sh"

conda activate vipe

# Fix for "Path too long" error: Use local /tmp on the node
export RAY_TMPDIR="/tmp/ray_vipe_$SLURM_JOB_ID"
mkdir -p $RAY_TMPDIR

# --- 2. Ray Cluster Setup ---
echo "Setting up Ray Cluster..."
echo "Job ID: $SLURM_JOB_ID"
echo "Array Task ID: $SLURM_ARRAY_TASK_ID"

nodes=$(scontrol show hostnames "$SLURM_JOB_NODELIST")
nodes_array=($nodes)
head_node=${nodes_array[0]}

head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)
port=6379
ip_head=$head_node_ip:$port
export ip_head
echo "Head node IP: $ip_head"

# Start Head Node
echo "Starting Ray Head on $head_node"
srun --nodes=1 --ntasks=1 -w "$head_node" \
    ray start --head --node-ip-address="$head_node_ip" --port=$port \
    --temp-dir="$RAY_TMPDIR" --block &

sleep 10 # Wait for head to initialize

# Start Worker Nodes (if -N > 1)
worker_num=$((SLURM_JOB_NUM_NODES - 1))
if [ $worker_num -gt 0 ]; then
    echo "Starting $worker_num Worker nodes"
    for ((i=1; i<=worker_num; i++)); do
        node_i=${nodes_array[$i]}
        echo "Starting Worker on $node_i"
        srun --nodes=1 --ntasks=1 -w "$node_i" \
             ray start --address "$ip_head" \
             --temp-dir="$RAY_TMPDIR" --block &
    done
    sleep 10 # Wait for workers to connect
fi

# --- 3. Run Annotation ---
echo "Cluster ready. Starting annotation..."

# Job parameters filled in by submit_all.sh
CHUNKS_PER_JOB=__CHUNKS_PER_JOB__
WINDOW_SIZE=__WINDOW_SIZE__
OVERLAP=__OVERLAP__

echo "Processing chunks: CHUNK_START to CHUNK_END (window=$WINDOW_SIZE, overlap=$OVERLAP, chunks/job=$CHUNKS_PER_JOB)"

cd "$MYHOME/projects/vipe"

# Paths
DATA_ROOT="$MYHOME/data/OmniWorld-Game"
OUTPUT_DIR="$MYHOME/data/OmniWorld-Game-vipe"
STATUS_DIR="$MYHOME/projects/vipe/slurm/omniworld/status"

python annotate_omniworld.py \
    --data-root "$DATA_ROOT" \
    --output-dir "$OUTPUT_DIR" \
    --chunk-start CHUNK_START \
    --chunk-end CHUNK_END \
    --window-size "$WINDOW_SIZE" \
    --overlap "$OVERLAP" \
    --per-frame-intrinsics \
    --use-ray \
    --skip-exists \
    --job-group "GROUP_ID" \
    --status-dir "$STATUS_DIR"

exit_code=$?

if [ $exit_code -eq 0 ]; then
    echo "Annotation finished successfully."
else
    echo "Annotation exited with code $exit_code."
fi

exit $exit_code
