#!/bin/bash
#SBATCH -A nvr_elm_llm
#SBATCH -p batch_singlenode,backfill_singlenode,backfill_block1,polar4,polar3,polar,grizzly
#SBATCH -t 04:00:00
#SBATCH -N 1
#SBATCH --gpus-per-node 8
#SBATCH --array=1-10%1
#SBATCH -J VIPE:Sekai-group_0097
#SBATCH -o logs/sekai_group_0097_%A_%a.out
#SBATCH -e logs/sekai_group_0097_%A_%a.err
#SBATCH --exclusive

# ============================================================================
# Sekai (sekai-real-walking-hq) Annotation Job Template
# This script is auto-generated by submit_all.sh
# group_0097 is replaced when generating job scripts
# ============================================================================

# --- 1. Environment Setup ---
export MYHOME="/lustre/fs12/portfolios/nvr/projects/nvr_elm_llm/users/haozhu"
MINIFORGE_ROOT="$MYHOME/miniforge3"
source "$MINIFORGE_ROOT/etc/profile.d/conda.sh"

conda activate vipe

# Fix for "Path too long" error: Use local /tmp on the node
export RAY_TMPDIR="/tmp/ray_vipe_$SLURM_JOB_ID"
mkdir -p $RAY_TMPDIR

# --- 2. Ray Cluster Setup ---
echo "Setting up Ray Cluster..."
echo "Job ID: $SLURM_JOB_ID"
echo "Array Task ID: $SLURM_ARRAY_TASK_ID"

nodes=$(scontrol show hostnames "$SLURM_JOB_NODELIST")
nodes_array=($nodes)
head_node=${nodes_array[0]}

head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)
port=6379
ip_head=$head_node_ip:$port
export ip_head
echo "Head node IP: $ip_head"

# Start Head Node
echo "Starting Head on $head_node"
srun --nodes=1 --ntasks=1 -w "$head_node" \
    ray start --head --node-ip-address="$head_node_ip" --port=$port \
    --temp-dir="$RAY_TMPDIR" --block &

sleep 10 # Wait for head to initialize

# Start Worker Nodes (if -N > 1)
worker_num=$((SLURM_JOB_NUM_NODES - 1))
if [ $worker_num -gt 0 ]; then
    echo "Starting $worker_num Worker nodes"
    for ((i=1; i<=worker_num; i++)); do
        node_i=${nodes_array[$i]}
        echo "Starting Worker on $node_i"
        srun --nodes=1 --ntasks=1 -w "$node_i" \
             ray start --address "$ip_head" \
             --temp-dir="$RAY_TMPDIR" --block &
    done
    sleep 10 # Wait for workers to connect
fi

# --- 3. Run Annotation ---
echo "Cluster ready. Starting annotation..."

cd "$MYHOME/projects/vipe"

# Paths
CSV_PATH="$MYHOME/projects/vipe/slurm/sekai/video_lists/group_0097.csv"
OUTPUT_PATH="$MYHOME/data/sekai-real-walking-hq/vipe_results/group_0097/"

echo "Processing videos from: $CSV_PATH"
echo "Output directory: $OUTPUT_PATH"

cmd="python run_ray.py \
    ray=true \
    prefilter=true \
    pipeline=default_perframe_intr \
    streams=raw_mp4_stream \
    streams.frame_end=-1 \
    streams.base_path=$CSV_PATH \
    pipeline.output.path=$OUTPUT_PATH"

echo "Executing: $cmd"
$cmd

exit_code=$?

if [ $exit_code -eq 0 ]; then
    echo "Annotation finished successfully."
else
    echo "Annotation exited with code $exit_code."
fi

exit $exit_code
